### ISSUE TITLE
Cant see the Admin page server error

### ISSUE THREAD

**Issue by adetheprince** [Powza/tm-07-real-estate#1]
Do we need to make or create a folder called Admin? where is the config or how to?
Would love to test this please, coz I have uploaded everything and only index and default page are working.
Thanks.

**Comment by Powza** [comment]
To be able to use this theme it requires DynamicIDX platform and database. The files here are only for setting up the theme in an active DynamicIDX platform similar to WordPress themes. DynamicIDX platform has a monthly cost.
